package com.academconnect.domain;

public enum TipoActividad {
    TRABAJO_CREADO,
    SOLICITUD_VINCULACION_ENVIADA,
    SOLICITUD_VINCULACION_APROBADA,
    SOLICITUD_VINCULACION_RECHAZADA,
    VERSION_SUBIDA,
    ASIGNACION_CREADA,
    EVALUACION_COMPLETADA,
    TRABAJO_APROBADO,
    TRABAJO_RECHAZADO,
    TEMPLATE_CREADO,
    SESION_PROGRAMADA,
    RECONOCIMIENTO_OTORGADO,
    RECONOCIMIENTO_REVOCADO,
    INVITACION_ORIENTACION_ENVIADA,
    INVITACION_ORIENTACION_ACEPTADA,
    INVITACION_ORIENTACION_RECHAZADA,
    INVITACION_ORIENTACION_CANCELADA,
    TRABAJO_PUBLICADO,
    TRABAJO_CERRADO,
    TRABAJO_EXPIRADO,
    SOLICITUD_VINCULACION_CANCELADA
}
