spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.com.academconnect=DEBUG

academconnect.security.cookie.secure=false
academconnect.security.cookie.same-site=Lax
